maxmind/MaxMind-DB-Reader-python

HISTORY.rst, maxminddb/compat.py, maxminddb/decoder.py, maxminddb/file.py, maxminddb/reader.py, tests/reader_test.py
After a fork, the file handle of both the parent and child process will share the same file table entry, which holds state such as the offset. There is unfortunately no way to clone the file table entry (dup only duplicates the file descriptor). This leads to corrupted reads when another process changes the offset unexpectedly. In Python 3.x, we use `pread` when available, as it does not rely on the offset in the file table. On Python's without `pread`, we rely on a lock. Reported in [#22 on GeoIP2-python](https://github.com/maxmind/GeoIP2-python/issues/22).
=> Use os.pread or a lock in MODE_FILE

README.rst, maxminddb/compat.py, maxminddb/reader.py, setup.py
Port of the 3.3+ ipaddress module to 2.6, 2.7, 3.2 now available, simplifies dependencies for end users who now have to have ipaddress and ipaddr installed to use this.
=> Use backport of ipaddress for Python 2 instead of ipaddr

.travis-yapf.sh, .travis.yml, HISTORY.rst, docs/conf.py, examples/benchmark.py, maxminddb/__init__.py, maxminddb/compat.py, maxminddb/decoder.py, maxminddb/reader.py, setup.py, tests/decoder_test.py, tests/reader_test.py
This makes the pure Python implementation consistent with the C
extension. The fact that these worked at all was an implementation
detail that changed over time.
This PR also includes a fix for #30.
=>  No longer allow ipaddress objects in pure Python implementation

.travis.yml, README.rst, requirements.txt, setup.py, tests/decoder_test.py
- snyk needs to check requirements.txt, so add one, but be warned it
isn't actually used as part of installing this project's dependencies;
see setup.py
- setup.py needs ipaddress for all python 2.x and python <3.3, but we're
only testing 3.x for versions 3.3 or greater. Therefore only check 2.7
since we'd expect the same snyk result for all python 2.x versions.
=> Run snyk checks on requirements, but only for python 2.7

HISTORY.rst, extension/maxminddb.c, maxminddb/compat.py, maxminddb/reader.py, tests/reader_test.py
=> Add support for ipaddress objects in "get" method

README.rst
Hello. I spent a few minutes tracking down why the extension was not being built for me. Turned out pip will silently fail to build the extension if `maxminddb.h` is missing. When installing `libmaxminddb` from a package, the header is included in a separate package. This is obvious, but the documentation seems to assume library installation via sources.
FWIW, I ran pip in verbose mode to get the build output / warning: `pip install -v maxminddb`.
I just added a note to the `README.rst` that may save someone some minutes in the future.
=> Add note about additional requirements.

.pylintrc, maxminddb/__init__.py, tests/reader_test.py
This exposes the ‘Reader’ class under its own name (instead of an alias)
and uses it as the return type for open_database(). In case the C
extension is used, cast that to the same ‘Reader’ type for type checking
purposes, since they share an identical API.
The benefits are that this avoids an unnecessary Union return type
(see e.g. python/mypy#1693) and doesn't
require internal types to be exposed with confusing names for type
checking purposes only.
The ‘Reader’ compat helper is unnecessary and can be dropped: the Python
Reader is always available and API compatible.
While at it, simplify and isort the imports.
=> Improve type checking: return ‘Reader’ from open_database()

maxminddb/__init__.py
Mypy reports attr-defined errors (via no_implicit_reexport) because the
‘maxminddb’ module uses implicit re-exports. Adding `__all__` makes the
exported API surface explicit, which avoids the type checking errors.
=> Expose __all__ to avoid type checking errors

setup.cfg
If I understand it correctly, all tests are passing without mocket for me and I don't see its usage anywhere in the codebase. So I believe it should be removed from test dependencies.
=> Remove unused mocket from test dependencies

tests/reader_test.py
On macOS, the default method for creating a new process is to use spawn instead of fork. When this occurs, arguments to the process target need to be pickled, but the test includes several unpicklable objects, such as local functions and mmaps.
We can fix the test's current assumptions by forcing "fork" instead of "spawn". I'm also open to fixing the test in other ways if we want to test that spawn works as well.
For reference, the original error signature:
```
obj = <Process name='Process-129' parent=38670 initial>, file = <_io.BytesIO object at 0x102294450>, protocol = None
def dump(obj, file, protocol=None):
'''Replacement for pickle.dump() using ForkingPickler.'''
>       ForkingPickler(file, protocol).dump(obj)
E       AttributeError: Can't pickle local object …
```
=> Fix multiprocessing tests on macOS.

HISTORY.rst, extension/maxminddb.c
From the Python 3.13 docs:
> Python.h no longer includes the <unistd.h> standard header file. If
> needed, it should now be included explicitly.
We use `access` from it.
=> Include unistd.h to fix Python 3.13 build

.github/workflows/address-sanitizer.yml, .github/workflows/clang-analyzer.yml, .github/workflows/codeql-analysis.yml, .github/workflows/create-wheels.yml, .github/workflows/test.yml, .gitmodules, HISTORY.rst, MANIFEST.in, README.rst, dev-bin/release.sh, extension/maxminddb.c, extension/maxminddb_config.h, pyproject.toml, setup.cfg, setup.py
- Drop Python 3.7 support
- Move project metadata to pyproject.toml
- Add support for building bdist_wheel
- Add workflow to build wheels
- Vendor libmaxminddb
- Increase verbosity when building wheels
- Build extension on PyPy
- Exclude extension/libmaxminddb/ from clang static analysis
- Do not set compile_args on Windows
=> Vendor libmaxminddb and produce binary wheels

MANIFEST.in, pyproject.toml
build seems to include everything by default for some reason.
=> Exclude dev config and scripts

.github/workflows/address-sanitizer.yml, tests/reader_test.py
- Don't hardcode module name
- Do not use tox for address sanitizer test
=> Fix address sanitizer test

.github/workflows/release.yml
Newer versions do not allow mutating an existing artfact. This breaks
our build. Although we could work around this, I am inclined to wait
to see if any best practices emerge when using the newer actions with
pypa/cibuildwheel and pypa/gh-action-pypi-publish.
=> Downgrade artifact actions

.github/workflows/release.yml
In 4.1, the "merge-multiple" feature was added to support this use case.
=> Upgrade to the v4 artifact actions again

HISTORY.rst, maxminddb/extension.pyi, maxminddb/reader.py
- Add type hints for Metadata
- Update maxminddb.extension type stubs
=> Improve extension type stubs

pyproject.toml
It's not required for production use, only for building. Instead, add the constraint part to `build_system -> requires` to save anyone having to ship setuptools in production builds.
Fixes #154.
=> Don't require setuptools in prod dependencies in pyproject.toml

.github/workflows/release.yml
Apparently, `macos-latest` means macOS 12. We need to to build on 14
Apple silicon support.
Fixes #152.
=> Build releases on macOS 13 and 14

.github/workflows/release.yml
This will build Linux wheels in multiple platforms using QEMU.
Example from [cibuildwheel](https://github.com/pypa/cibuildwheel/blob/070e744d267952ab3b86ed434d5796b707e497af/examples/github-with-qemu.yml#L17-L28)
fixes #159
=> Build wheels in multiple platforms with QEMU

.github/workflows/test-libmaxminddb.yml, .github/workflows/test.yml, HISTORY.rst, README.rst, docs/index.rst, maxminddb/__init__.py, maxminddb/decoder.py, maxminddb/errors.py, maxminddb/extension.pyi, maxminddb/reader.py, maxminddb/types.py, pyproject.toml, setup.cfg, tests/reader_test.py, uv.lock
- **Drop 3.8 support**
- **Add dev deps to pyproject.toml**
- **Minor doc rendering improvements**
- **Minor auto-fixes from ruff**
=> Add dev deps and minor doc improvements

.github/workflows/clang-analyzer.yml, .github/workflows/codeql-analysis.yml, .github/workflows/test-libmaxminddb.yml, .gitignore, HISTORY.rst, extension/maxminddb.c, pyproject.toml
- **Ignore clangd conf file**
- **Fix license config deprecation warnings**
- **Correctly handle null check of entry_data_list**
=> Correctly handle null check of entry_data_list

HISTORY.rst, README.rst, maxminddb/__init__.py, pyproject.toml
- **Set release date**
- **Update for v2.7.0**
=> Release 2.7.0

.github/workflows/test-libmaxminddb.yml, .github/workflows/test.yml, pyproject.toml, setup.cfg
- **Modernize tox config and switch to tox-gh**
- **Remove duplicate setuptools setup.cfg**
=> Modernize tox config and switch to tox-gh

.github/workflows/release.yml, HISTORY.rst
- **Bump pypa/cibuildwheel from 2.23.3 to 3.0.0**
- **Update cibuildwheel config for 3.0**
=> Update to cibuildwheel 3.0.0

.github/workflows/release.yml, .github/workflows/test-libmaxminddb.yml, .github/workflows/test.yml, HISTORY.rst, pyproject.toml
- **Test on 3.14**
- **Build Android wheels**
=> Add Android wheels and test on 3.14

.github/workflows/release.yml, HISTORY.rst, maxminddb/__init__.py, pyproject.toml
Our `cibuildwheel` 3.0.0 configuration changed the artifact names,
causing them to not be uploaded.
Fixes #225.
=> Upload binary wheels to PyPI again

.gitmodules
This makes `git clone --recurse-submodules` fail if it's run in an environment where an SSH key registered with GitHub isn't available. That seems unnecessary in this case, since the repository is public.
=> Don't use git@ for submodule
